language: node_js
node_js:
  - v10
install:
  - npm i
script:
  - npm run build
  - npm t
before_deploy: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  on:
    branch: master
